# Generated by Django 4.0.4 on 2022-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('dateSent', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sent_emails',
            },
        ),
    ]
